PYRUN = pipenv run

style:
	isort .
	black .

all:
	$(PYRUN) python 01/calories.py
	$(PYRUN) python 02/rps.py
	$(PYRUN) python 03/backpack.py
	$(PYRUN) python 04/cleanup.py
	$(PYRUN) python 05/moveit.py
	$(PYRUN) python 06/tuning.py
